<a href="https://colab.research.google.com/github/AdrianaGLG/Math4Data/blob/main/Notebook_5_Resoluci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

1+2

In [3]:
import pandas as pd
import numpy as np
#importar librerias

In [ ]:
#no funciona


In [8]:
#a
#b
'''
Crear un arreglo de ceros de longitud 12
Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Crear un arreglo que tenga los números del 10 al 49
Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Calcular la media de un arreglo usando np.sum
Calcular la varianza de un arreglo usando np.sum y np.mean
Crear un array de números aleatorios usando np.random.randn.
'''
variable = 1+2
variable

3

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


lo que sea

In [ ]:
# comentar
1+2

------
------
# titulo
consigna

-------------------
------------------
# EJERCICIO 1
1. Crear un arreglo de ceros de longitud 12

In [16]:
# 1. Crear un arreglo de ceros de longitud 12

#import numpy as np
arreglo_ej_1 = np.zeros(5)
#variable = np.zeros(cantidad q querramos) # arreglo de ceros con la cantidad deseada
print(arreglo_ej_1)


[0. 0. 0. 0. 0.]


In [9]:
# Alternativa
arreglo = [1] * 12
print(arreglo)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
# Alternativa
arreglo2 = [0 for _ in range(12)]
print(arreglo2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
arreglo3 = []
for _ in range(12):
    arreglo3.append(0)
print (arreglo3)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
from itertools import repeat #esto no lo vimos
arreglo4 = list(repeat(0, 12))
print (arreglo4)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
import array #  biblioteca de Python que nos permite crear arreglos de datos homogéneos

# Crear un arreglo de ceros de tipo float ('f')
arreglo6 = array.array('f', [0] * 12)

#enteros de 32 bits con longitud 12
#arreglo_enteros = array.array('i', [0] * 12)

# arreglo de doble precisión de 64 bits con longitud 12
#arreglo_doble_precision = array.array('d', [0] * 12)

print (arreglo6)

array('f', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])


In [ ]:
type(arreglo6)

array.array

-----------------------------
-----------------------------
### EJERCICIO 2

2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [28]:
# crear una lista
arregloa = [0] * 10
arreglob = arregloa
arreglob[4] = 10 # posicion 5 = indice 4

print(arreglob)

[0, 0, 0, 0, 10, 0, 0, 0, 0, 0]


In [29]:
# Usar Numpy
#import numpy as np

arreglo2 = np.zeros(10)
arreglo2[4] = 10
arreglo2[5] = 20
#variable [numero de posicion]= valor que quiero agregar
print(arreglo2)

[ 0.  0.  0.  0. 10. 20.  0.  0.  0.  0.]


In [ ]:
# Libreria array
import array

arreglo3 = array.array('f', [0] * 10) # arreglo de tipo floats
arreglo3[4] = 10

print(arreglo3)

array('f', [0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0])


-----------
-----------
### EJERCICIO 3

3. Crear un arreglo que tenga los números del 10 al 49

In [ ]:
# Listas
arreglo = list(range(10, 50))
print(arreglo)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [31]:
# Usando Numpy
#import numpy as np

arreglo_ej_3 = np.arange(10, 14)
print(arreglo_ej_3)

[10 11 12 13]


In [ ]:
# Usando array
import array

arreglo2 = array.array('i', range(10, 50))
print(arreglo2)


array('i', [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])


-----------
-----------
### EJERCICIO 4

4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [ ]:
# Crear una lista
arreglo = [[i * 3 + j for j in range(3)] for i in range(3)]
print(arreglo)
print(type(arreglo))

# i * 3 + j - (i: fila, j: columna) en i:0 --> los numeros generados son: 0 * 3 + 0 = 0 // 0 * 3 + 1 = 1 // y 0 * 3 + 2 = 2
# en i:1 --> los numeros son: 1 * 3 + 0 = 3, 1 * 3 + 1 = 4, y 1 * 3 + 2 = 5
# en i:2 --> 2 * 3 + 0 = 6, 2 * 3 + 1 = 7, y 2 * 3 + 2 = 8

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'list'>


In [36]:
# Desde una lista - transformar con np
#lista = list(range(9))

# transformar usando Np
#import numpy as np
arreglo_ej_4 = np.arange(0, 8)
arreglo = np.array(arreglo_ej_4) # convertir
#arreglo_2d = arreglo.reshape(3, 3) # transformar en 3,3

#print(arreglo_2d)
#print(type(arreglo_2d))

In [37]:
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Crear un diccionario - transformar con np
diccionario = {
    0: [0, 1, 2],
    1: [3, 4, 5],
    2: [6, 7, 8]
}

import numpy as np
lista_2d = [diccionario[i] for i in range(3)]
arreglo_2d = np.array(lista_2d) # transformar
print(arreglo_2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Usar Numpy - lo mas fácil!!
import numpy as np

arreglo = np.arange(9).reshape(3, 3) # arange: arreglo de 0 a 8 - reshape: organiza
print(arreglo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Usar array
import array

arreglo = [array.array('i', range(i * 3, i * 3 + 3)) for i in range(3)]

for fila in arreglo:
    print(fila)

array('i', [0, 1, 2])
array('i', [3, 4, 5])
array('i', [6, 7, 8])


-----------
-----------
### EJERCICIO 5

5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [43]:
# Usando Np
#import numpy as np

arreglo = np.random.random(5)
print("El arreglo:", arreglo)


El arreglo: [0.91100629 0.61671943 0.60678774 0.76002746 0.75812933]


In [51]:
# Media
media = np.mean(arreglo)
print("Media:", media, "ese es el valor")


Media: 0.7305340510764098 ese es el valor


In [50]:
# Varianza
varianza = np.var(arreglo)
varianza


0.012493701594087234

In [ ]:
import random

# Arregleo aleatorio
arreglo = [random.random() for _ in range(100)]

# Media
media = sum(arreglo) / len(arreglo)

# Varianza
media_cuadrada = sum(x ** 2 for x in arreglo) / len(arreglo)
varianza = media_cuadrada - media ** 2

# Ver resultado
print("Arreglo de números aleatorios:", arreglo)
print("Media:", media)
print("Varianza:", varianza)


Arreglo de números aleatorios: [0.9992254295057238, 0.28101210881542327, 0.2916927020167479, 0.7000521424164173, 0.8708553668004182, 0.5872957185987951, 0.5125938689393398, 0.5584225741093316, 0.595534143896906, 0.7141357769478508, 0.2026477702516487, 0.4534551251754889, 0.6080519101009543, 0.19063051664403696, 0.8057240279373329, 0.414409830093716, 0.36377630971602104, 0.40125250601826945, 0.8588239629642326, 0.3386562335447054, 0.8454077256636823, 0.16104982353917474, 0.1949025939455803, 0.5000066471180231, 0.1717762200323083, 0.6235401418553376, 0.3054461027379255, 0.45953355529302176, 0.9464943757427592, 0.39785681016737173, 0.7700990103512747, 0.10424670360662114, 0.253718680826438, 0.37378414551107364, 0.7008332014883625, 0.5885022645797324, 0.22756740501875516, 0.03958874870619533, 0.07403292452523114, 0.9150538283034785, 0.8454451018208208, 0.08750621867874975, 0.9286055449722961, 0.9934637360957946, 0.8664180652452286, 0.667579346035923, 0.15090026072196483, 0.5363943912670458

In [ ]:
import random
import statistics

# Arreglo
arreglo = [random.random() for _ in range(100)]
# random.random(): función que devuelve un número aleatorio entre 0 y 1 (incluyendo 0 pero excluyendo 1)
# for _ in range(100): bucle for - se ejecuta 100 veces. Se genera un número aleatorio usando random.random() y se agrega a la lista
# no se necesita el nombre, por eso se puede usar _

# Media y varianza
media = statistics.mean(arreglo)
varianza = statistics.variance(arreglo)

# Resultados
print("Arreglo de números aleatorios:", arreglo)
print("Media:", media)
print("Varianza:", varianza)


Arreglo de números aleatorios: [0.7730763333468915, 0.3269144180264373, 0.4432355546237726, 0.5834896073592267, 0.5997295269143205, 0.3892727760688547, 0.05387662930893744, 0.12591892014903594, 0.5070178350302599, 0.49372953153876, 0.010335504692087993, 0.4776692845917835, 0.13654635677622362, 0.46621866772203957, 0.05230124432405914, 0.10833774739925561, 0.17940920712051278, 0.6146495233239445, 0.20495047397888544, 0.7386325567259853, 0.7489089959137637, 0.11413944164725953, 0.7017010874034582, 0.09738845572696331, 0.39661047158290264, 0.5757260521124986, 0.8762750034745429, 0.5953480973965293, 0.9617800611870535, 0.23388970002577436, 0.4757554587431473, 0.3829862683234003, 0.4788286293955917, 0.23733872419467217, 0.5479414143722148, 0.6397297867295982, 0.5119594815112392, 0.6959498964264296, 0.2840291051047086, 0.16446691717835438, 0.7325975203039085, 0.8399797446256724, 0.3735987403546822, 0.7588602364195834, 0.8508406097093592, 0.380701935502874, 0.7960919158525731, 0.4180393460703

In [ ]:
import numpy as np
from scipy import stats

arreglo = stats.norm.rvs(size=100)

media = np.mean(arreglo)
varianza = np.var(arreglo)

print("Arreglo de números aleatorios:", arreglo)
print("Media:", media)
print("Varianza:", varianza)


Arreglo de números aleatorios: [ 0.23815685  1.63679201  0.23463216 -0.32522062  0.96933103 -0.92755985
  0.70834008 -0.10404761 -0.53087771 -0.27741597 -1.24830976  0.252775
  1.43828227  0.02255792 -0.58801891  3.2028218  -0.50811744 -0.48109667
  1.67905533  1.36851601  0.01064121  2.25427404 -0.65852722 -1.13931462
  1.04336629 -0.32146169  0.95374996  1.30981477 -0.10066883  0.02175611
  0.14095439 -1.64064547  0.73883081 -1.5693812  -0.16217007 -1.18393817
 -1.04985468  0.29670741 -1.22033209 -0.29870793  0.60357772  2.45859646
 -0.83058084  0.31798431  0.10781257 -1.61246119  0.02352954 -0.03711819
 -1.12974833  0.62318108 -1.19297253  0.7192971  -2.42403975 -1.33654562
 -1.71207711 -0.21193402 -0.65550527 -0.52023305 -0.5784969  -0.60948669
 -0.97649025  1.2198581  -0.20753995 -0.5844987   0.06410299 -0.5574203
 -1.19054783 -0.42812512  2.07714953  0.17337796 -0.06247245  0.65758161
  0.73892801  0.13735595  0.00960403 -0.48473426  1.87080797  1.46149416
 -0.20387865  1.8577440

-----------
-----------
### EJERCICIO 6

6. Calcular la media de un arreglo usando np.sum

In [56]:
#import numpy as np

arreglo = np.random.random(10)

suma = np.sum(arreglo) # np.sum
tamano = np.size(arreglo) # size
media = suma / tamano

# Ver resultado
print("Media del arreglo:", media)
print (arreglo)
print (suma)
print (tamano)


Media del arreglo: 0.5735571478265957
[0.73277037 0.73556212 0.35307804 0.61954798 0.26294026 0.60332925
 0.2665036  0.55362396 0.93544135 0.67277454]
5.735571478265958
10


In [ ]:
# sin usar np.sum
import numpy as np

arreglo = np.random.random(100)

media = np.mean(arreglo)

print("Media del arreglo:", media)


Media del arreglo: 0.45750895347660403


In [ ]:
import numpy as np

arreglo = np.random.random(100)

suma = np.sum(arreglo)
longitud = arreglo.shape[0] # shape
media = suma / longitud

print("Media del arreglo:", media)


Media del arreglo: 0.5188153708649537


In [ ]:
import numpy as np

arreglo = np.random.random((10, 10)) #2d: 10x10

suma = np.sum(arreglo)
tamano = np.size(arreglo) #size
media = suma / tamano

print("Media del arreglo:", media)


Media del arreglo: 0.4481746854813853


-----------
-----------
### EJERCICIO 7

7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [ ]:
import numpy as np

arreglo = np.random.random(100)

media = np.mean(arreglo)
suma_cuadrados_diferencias = np.sum((arreglo - media) ** 2)
varianza = suma_cuadrados_diferencias / len(arreglo)

print("Varianza del arreglo:", varianza)


Varianza del arreglo: 0.10025684956534466


In [ ]:
import numpy as np

arreglo = np.random.random(100)

media = np.mean(arreglo)
suma_cuadrados_diferencias = np.sum((arreglo - media) ** 2)
varianza_muestra = suma_cuadrados_diferencias / (len(arreglo) - 1) # estimación sin sesgo de la varianza de la muestra

print("Varianza de la muestra del arreglo:", varianza_muestra)


Varianza de la muestra del arreglo: 0.07532203235325068


In [ ]:
import numpy as np

arreglo = np.random.random(100)
pesos = np.random.random(100)

media_ponderada = np.sum(arreglo * pesos) / np.sum(pesos)

suma_cuadrados_diferencias_ponderada = np.sum(pesos * (arreglo - media_ponderada) ** 2)

varianza_ponderada = suma_cuadrados_diferencias_ponderada / np.sum(pesos)

print("Varianza ponderada del arreglo:", varianza_ponderada)


Varianza ponderada del arreglo: 0.08145521083151065


-----------
-----------
### EJERCICIO 8

8. Crear un array de números aleatorios usando np.random.randn.

In [ ]:
import numpy as np

arreglo = np.random.randn(10)
print("Array unidimensional:", arreglo)


Array unidimensional: [-0.94280963 -0.84884857 -0.19564391  1.77704041  0.33619667  0.33428049
  0.17673161  0.98782943  2.03539633  0.23870928]


In [ ]:
import numpy as np

matriz = np.random.randn(3, 3)

print("Array bidimensional (3x3):")
print(matriz)


Array bidimensional (3x3):
[[-0.42157472 -0.39367397  0.51720271]
 [ 0.12625266  0.56641679 -0.52882603]
 [ 0.17815134  0.461321   -0.03814226]]


In [ ]:
import numpy as np

# Array tridimensional de 2x3x4 números aleatorios de una distribución normal estándar
tensor = np.random.randn(2, 3, 4)

print("Array tridimensional (2x3x4):")
print(tensor)


Array tridimensional (2x3x4):
[[[-1.15406291 -0.07475927  0.90204572  2.75423789]
  [-1.75006764  1.99496454  0.45581366 -1.16222215]
  [ 0.95565628  0.98375304  0.73824164 -1.31898615]]

 [[-0.1100303   0.64104062  0.14232338  0.83069197]
  [-0.6611267  -1.69780731 -0.5128665   0.91883533]
  [ 0.65412437  0.45047526  0.67741978  1.02454402]]]


In [ ]:
import numpy as np

# Array de 4 dimensiones (2, 3, 4, 5) de números aleatorios de una distribución normal estándar
array_4d = np.random.randn(2, 3, 4, 5)

print("Array de 4 dimensiones (2x3x4x5):")
print(array_4d)


Array de 4 dimensiones (2x3x4x5):
[[[[ 9.16375256e-02  1.34304099e-02 -4.66067084e-02 -1.65318007e+00
     9.12925212e-01]
   [-5.67840553e-01  8.81735935e-02 -5.23771502e-01  1.05754915e+00
    -3.61260108e-01]
   [ 3.32904118e-01 -1.13866889e+00  8.75427143e-01  1.29087129e+00
     1.48201047e-01]
   [-3.97721910e-02  9.36896650e-01 -4.40517744e-01  2.31773314e-01
     4.31465656e-01]]

  [[ 8.33875741e-01 -1.29236509e+00  2.13629124e+00  1.21059922e+00
    -4.92034158e-01]
   [-8.12583757e-01  1.89149427e-01  1.34975819e+00  2.06482185e-02
    -1.37790287e+00]
   [-2.14962086e+00  7.72406266e-03  2.03598610e-01  1.90075709e+00
    -5.16861484e-01]
   [ 1.08050499e+00 -1.12189559e+00  2.28917550e+00  4.42870641e-01
     8.55984650e-01]]

  [[ 5.29373244e-01 -1.28707292e+00  1.92296239e+00  9.42256483e-01
    -1.00123832e+00]
   [-9.80332027e-01 -5.32562507e-01 -1.62758493e+00 -1.02584575e+00
    -3.41754385e-01]
   [-1.09910311e+00 -1.38893013e+00  9.68993717e-01  3.11976424e-01
    